export const VIDEO_ANALYSIS_COLORS = {
  // Primary colors
  primary: '#00F5A0',
  primaryGlow: 'rgba(0, 245, 160, 0.4)',
  secondary: '#00DDFF',
  secondaryGlow: 'rgba(0, 221, 255, 0.4)',

  // Background colors
  background: '#111827',
  backgroundTranslucent: 'rgba(17, 24, 39, 0.95)',
  surface: 'rgba(31, 41, 55, 0.85)',
  surfaceElevated: 'rgba(55, 65, 81, 0.6)',
  surfaceSolid: '#1F2937',

  // Text colors
  textPrimary: '#FFFFFF',
  textSecondary: '#9CA3AF',
  textMuted: '#6B7280',

  // Border colors
  border: 'rgba(75, 85, 99, 0.3)',
  borderActive: 'rgba(75, 85, 99, 0.5)',

  // Status colors
  statusGood: '#00F5A0',
  statusGoodBg: 'rgba(0, 245, 160, 0.1)',
  statusWarning: '#FFB800',
  statusWarningBg: 'rgba(255, 184, 0, 0.1)',
  statusError: '#FF3D71',
  statusErrorBg: 'rgba(255, 61, 113, 0.1)',

  // Accent colors
  accentCyan: '#06B6D4',
  accentViolet: '#8B5CF6',
  accentAmber: '#F59E0B',

  // Skeleton colors
  skeletonHighlight: '#00F5A0',
  skeletonBase: '#FFFFFF',

  // Toggle controls
  toggleActiveBg: 'rgba(0, 245, 160, 0.2)',
  toggleActiveBorder: 'rgba(0, 245, 160, 0.4)',
  toggleInactiveBg: 'rgba(31, 41, 55, 0.6)',
  toggleInactiveBorder: 'rgba(75, 85, 99, 0.5)',

  // Slider controls
  sliderTrack: 'rgba(55, 65, 81, 0.8)',
  sliderFill: '#00F5A0',
  sliderThumb: '#FFFFFF',

  // Focus mode
  focusModeHighlight: '#00DDFF',
  focusModeHighlightGlow: 'rgba(0, 221, 255, 0.4)',
  problemJointPulse: 'rgba(255, 61, 113, 0.6)',

  // Skeleton overlay specific
  skeletonOverlayBase: '#FFFFFF',
  skeletonOverlayActive: '#00F5A0',

  // Timeline colors
  videoOverlay: 'rgba(0, 0, 0, 0.4)',
  timelineTrack: 'rgba(75, 85, 99, 0.4)',
  timelineProgress: '#00F5A0',
  timelineMarker: '#FF3D71',
  timelineMarkerQueued: '#FFB800',

  // Voice feedback colors
  audioSpeaking: '#00ddff',
  audioSpeakingGlow: 'rgba(0, 221, 255, 0.4)',
  audioMuted: '#6B7280',
  audioPaused: '#FFB800',
  successGlow: 'rgba(0, 245, 160, 0.4)',
  warningGlow: 'rgba(255, 184, 0, 0.4)',
  dangerGlow: 'rgba(255, 61, 113, 0.4)',
} as const;

export const COMPARISON_COLORS = {
  sessionA: '#3b82f6',        // Blue for first session
  sessionB: '#8b5cf6',        // Violet for second session
  sessionC: '#f59e0b',        // Amber for third session (if comparing 3)
  trendImproving: '#00F5A0',
  trendDeclining: '#FF3D71',
  trendStable: '#9CA3AF',
} as const;

export const PLAYBACK_SPEEDS = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2] as const;

export const TRANSLATIONS = {
  ko: {
    pageTitle: '비디오 분석',
    originalVideo: '원본 비디오',
    skeletonOverlay: '스켈레톤 오버레이',
    reps: '반복',
    repNumber: '반복 #{number}',
    score: '점수',
    formFeedback: '자세 피드백',
    noIssues: '현재 시점에 이슈가 없습니다',
    angleMeasurements: '각도 측정',
    exportPdf: 'PDF 내보내기',
    generating: '생성 중...',
    overallScore: '전체 점수',
    perRepBreakdown: '반복별 분석',
    problemMoments: '문제 구간',
    recommendations: '개선 권장사항',
    noData: '분석 데이터가 없습니다',
    loadingAnalysis: '분석 데이터 로딩 중...',
    play: '재생',
    pause: '일시정지',
    speed: '속도',
    jumpToRep: '반복으로 이동',
    duration: '지속시간',
    phase: '단계',
    issues: '이슈',
    back: '뒤로',
    problemMarker: '문제 구간',
    markerScore: '점수',
    markerIssues: '문제점',
    clickToSeek: '클릭하여 이동',
    errorLevel: '심각',
    warningLevel: '주의',
    viewModeSideBySide: '나란히 보기',
    viewModeOverlay: '오버레이',
    opacity: '투명도',
    jointAngles: '관절 각도',
    focusMode: '포커스 모드',
    showAngles: '각도 표시',
    hideAngles: '각도 숨기기',
    focusProblems: '문제 부위 강조',
    viewControls: '보기 설정',
  },
  en: {
    pageTitle: 'Video Analysis',
    originalVideo: 'Original Video',
    skeletonOverlay: 'Skeleton Overlay',
    reps: 'Reps',
    repNumber: 'Rep #{number}',
    score: 'Score',
    formFeedback: 'Form Feedback',
    noIssues: 'No issues at current timestamp',
    angleMeasurements: 'Angle Measurements',
    exportPdf: 'Export PDF',
    generating: 'Generating...',
    overallScore: 'Overall Score',
    perRepBreakdown: 'Per-Rep Breakdown',
    problemMoments: 'Problem Moments',
    recommendations: 'Recommendations',
    noData: 'No analysis data available',
    loadingAnalysis: 'Loading analysis data...',
    play: 'Play',
    pause: 'Pause',
    speed: 'Speed',
    jumpToRep: 'Jump to rep',
    duration: 'Duration',
    phase: 'Phase',
    issues: 'Issues',
    back: 'Back',
    problemMarker: 'Problem Moment',
    markerScore: 'Score',
    markerIssues: 'Issues',
    clickToSeek: 'Click to seek',
    errorLevel: 'Error',
    warningLevel: 'Warning',
    viewModeSideBySide: 'Side by Side',
    viewModeOverlay: 'Overlay',
    opacity: 'Opacity',
    jointAngles: 'Joint Angles',
    focusMode: 'Focus Mode',
    showAngles: 'Show Angles',
    hideAngles: 'Hide Angles',
    focusProblems: 'Highlight Problems',
    viewControls: 'View Controls',
  },
} as const;

export const SESSION_HISTORY_TRANSLATIONS = {
  ko: {
    sessionHistory: '세션 기록',
    noHistory: '아직 분석 기록이 없습니다',
    startAnalysis: '분석 시작하기',
    compareSelected: '선택 항목 비교',
    selectForCompare: '비교를 위해 선택',
    deleteSession: '세션 삭제',
    deleteConfirmTitle: '세션을 삭제하시겠습니까?',
    deleteConfirmMessage: '이 작업은 취소할 수 없습니다.',
    cancel: '취소',
    delete: '삭제',
    export: '내보내기',
    exportAll: '전체 내보내기',
    compareWithPrevious: '이전 기록과 비교',
    noMatchingSessions: '비교할 수 있는 동일 운동 기록이 없습니다',
    improvement: '향상',
    decline: '하락',
    stable: '유지',
    sessionDate: '세션 날짜',
    overallProgress: '전체 진행 상황',
    scoreProgression: '점수 변화',
    repScoreComparison: '반복별 점수 비교',
    consistencyTrend: '일관성 추세',
    commonIssues: '공통 문제점',
    resolvedIssues: '개선된 문제점',
    loadMore: '더 보기',
    selected: '선택됨',
    maxSelectionReached: '최대 3개까지 선택 가능합니다',
    reps: '반복',
    duration: '시간',
    consistency: '일관성',
    high: '높음',
    medium: '중간',
    low: '낮음',
    filterAll: '전체',
    sortNewest: '최신순',
    sortOldest: '오래된순',
    sortHighScore: '높은 점수순',
    sortLowScore: '낮은 점수순',
    squat: '스쿼트',
    lunge: '런지',
    deadlift: '데드리프트',
    pushup: '푸시업',
    plank: '플랭크',
    unknown: '기타',
    close: '닫기',
    averageImprovement: '평균 향상',
    points: '점',
    totalSessions: '총 세션',
    bestSession: '최고 기록',
    score: '점수',
  },
  en: {
    sessionHistory: 'Session History',
    noHistory: 'No analysis history yet',
    startAnalysis: 'Start Analysis',
    compareSelected: 'Compare Selected',
    selectForCompare: 'Select for Compare',
    deleteSession: 'Delete Session',
    deleteConfirmTitle: 'Delete this session?',
    deleteConfirmMessage: 'This action cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    export: 'Export',
    exportAll: 'Export All',
    compareWithPrevious: 'Compare with Previous',
    noMatchingSessions: 'No matching sessions for this exercise type',
    improvement: 'Improvement',
    decline: 'Decline',
    stable: 'Stable',
    sessionDate: 'Session Date',
    overallProgress: 'Overall Progress',
    scoreProgression: 'Score Progression',
    repScoreComparison: 'Per-Rep Score Comparison',
    consistencyTrend: 'Consistency Trend',
    commonIssues: 'Common Issues',
    resolvedIssues: 'Resolved Issues',
    loadMore: 'Load More',
    selected: 'selected',
    maxSelectionReached: 'Maximum 3 sessions can be selected',
    reps: 'Reps',
    duration: 'Duration',
    consistency: 'Consistency',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    filterAll: 'All',
    sortNewest: 'Newest',
    sortOldest: 'Oldest',
    sortHighScore: 'Highest Score',
    sortLowScore: 'Lowest Score',
    squat: 'Squat',
    lunge: 'Lunge',
    deadlift: 'Deadlift',
    pushup: 'Pushup',
    plank: 'Plank',
    unknown: 'Other',
    close: 'Close',
    averageImprovement: 'Average Improvement',
    points: 'pts',
    totalSessions: 'Total Sessions',
    bestSession: 'Best Session',
    score: 'Score',
  },
} as const;
