import type { Pose, Keypoint } from '@tensorflow-models/pose-detection'

export interface Keypoint3D extends Keypoint {
  z?: number
}

export interface Pose3D extends Pose {
  keypoints3D?: Keypoint3D[]
}

export type LoadingState = 'idle' | 'loading-model' | 'loading-camera' | 'ready' | 'error'

export interface PoseDetectionState {
  pose: Pose3D | null
  fps: number
  loadingState: LoadingState
  error: string | null
}

export interface WebcamState {
  stream: MediaStream | null
  isReady: boolean
  error: string | null
}

export interface PoseDetectorConfig {
  mirrored?: boolean
  showSkeleton?: boolean
  showKeypoints?: boolean
  minPoseScore?: number
  minKeypointScore?: number
}

// BlazePose 33 keypoint indices
export const BLAZEPOSE_KEYPOINTS = {
  NOSE: 0,
  LEFT_EYE_INNER: 1,
  LEFT_EYE: 2,
  LEFT_EYE_OUTER: 3,
  RIGHT_EYE_INNER: 4,
  RIGHT_EYE: 5,
  RIGHT_EYE_OUTER: 6,
  LEFT_EAR: 7,
  RIGHT_EAR: 8,
  MOUTH_LEFT: 9,
  MOUTH_RIGHT: 10,
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_ELBOW: 13,
  RIGHT_ELBOW: 14,
  LEFT_WRIST: 15,
  RIGHT_WRIST: 16,
  LEFT_PINKY: 17,
  RIGHT_PINKY: 18,
  LEFT_INDEX: 19,
  RIGHT_INDEX: 20,
  LEFT_THUMB: 21,
  RIGHT_THUMB: 22,
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  LEFT_KNEE: 25,
  RIGHT_KNEE: 26,
  LEFT_ANKLE: 27,
  RIGHT_ANKLE: 28,
  LEFT_HEEL: 29,
  RIGHT_HEEL: 30,
  LEFT_FOOT_INDEX: 31,
  RIGHT_FOOT_INDEX: 32,
} as const

// Skeleton connections for drawing
export const SKELETON_CONNECTIONS: [number, number][] = [
  // Face
  [BLAZEPOSE_KEYPOINTS.LEFT_EAR, BLAZEPOSE_KEYPOINTS.LEFT_EYE_OUTER],
  [BLAZEPOSE_KEYPOINTS.LEFT_EYE_OUTER, BLAZEPOSE_KEYPOINTS.LEFT_EYE],
  [BLAZEPOSE_KEYPOINTS.LEFT_EYE, BLAZEPOSE_KEYPOINTS.LEFT_EYE_INNER],
  [BLAZEPOSE_KEYPOINTS.LEFT_EYE_INNER, BLAZEPOSE_KEYPOINTS.NOSE],
  [BLAZEPOSE_KEYPOINTS.NOSE, BLAZEPOSE_KEYPOINTS.RIGHT_EYE_INNER],
  [BLAZEPOSE_KEYPOINTS.RIGHT_EYE_INNER, BLAZEPOSE_KEYPOINTS.RIGHT_EYE],
  [BLAZEPOSE_KEYPOINTS.RIGHT_EYE, BLAZEPOSE_KEYPOINTS.RIGHT_EYE_OUTER],
  [BLAZEPOSE_KEYPOINTS.RIGHT_EYE_OUTER, BLAZEPOSE_KEYPOINTS.RIGHT_EAR],
  [BLAZEPOSE_KEYPOINTS.MOUTH_LEFT, BLAZEPOSE_KEYPOINTS.MOUTH_RIGHT],

  // Torso
  [BLAZEPOSE_KEYPOINTS.LEFT_SHOULDER, BLAZEPOSE_KEYPOINTS.RIGHT_SHOULDER],
  [BLAZEPOSE_KEYPOINTS.LEFT_SHOULDER, BLAZEPOSE_KEYPOINTS.LEFT_HIP],
  [BLAZEPOSE_KEYPOINTS.RIGHT_SHOULDER, BLAZEPOSE_KEYPOINTS.RIGHT_HIP],
  [BLAZEPOSE_KEYPOINTS.LEFT_HIP, BLAZEPOSE_KEYPOINTS.RIGHT_HIP],

  // Left arm
  [BLAZEPOSE_KEYPOINTS.LEFT_SHOULDER, BLAZEPOSE_KEYPOINTS.LEFT_ELBOW],
  [BLAZEPOSE_KEYPOINTS.LEFT_ELBOW, BLAZEPOSE_KEYPOINTS.LEFT_WRIST],
  [BLAZEPOSE_KEYPOINTS.LEFT_WRIST, BLAZEPOSE_KEYPOINTS.LEFT_PINKY],
  [BLAZEPOSE_KEYPOINTS.LEFT_WRIST, BLAZEPOSE_KEYPOINTS.LEFT_INDEX],
  [BLAZEPOSE_KEYPOINTS.LEFT_WRIST, BLAZEPOSE_KEYPOINTS.LEFT_THUMB],
  [BLAZEPOSE_KEYPOINTS.LEFT_PINKY, BLAZEPOSE_KEYPOINTS.LEFT_INDEX],

  // Right arm
  [BLAZEPOSE_KEYPOINTS.RIGHT_SHOULDER, BLAZEPOSE_KEYPOINTS.RIGHT_ELBOW],
  [BLAZEPOSE_KEYPOINTS.RIGHT_ELBOW, BLAZEPOSE_KEYPOINTS.RIGHT_WRIST],
  [BLAZEPOSE_KEYPOINTS.RIGHT_WRIST, BLAZEPOSE_KEYPOINTS.RIGHT_PINKY],
  [BLAZEPOSE_KEYPOINTS.RIGHT_WRIST, BLAZEPOSE_KEYPOINTS.RIGHT_INDEX],
  [BLAZEPOSE_KEYPOINTS.RIGHT_WRIST, BLAZEPOSE_KEYPOINTS.RIGHT_THUMB],
  [BLAZEPOSE_KEYPOINTS.RIGHT_PINKY, BLAZEPOSE_KEYPOINTS.RIGHT_INDEX],

  // Left leg
  [BLAZEPOSE_KEYPOINTS.LEFT_HIP, BLAZEPOSE_KEYPOINTS.LEFT_KNEE],
  [BLAZEPOSE_KEYPOINTS.LEFT_KNEE, BLAZEPOSE_KEYPOINTS.LEFT_ANKLE],
  [BLAZEPOSE_KEYPOINTS.LEFT_ANKLE, BLAZEPOSE_KEYPOINTS.LEFT_HEEL],
  [BLAZEPOSE_KEYPOINTS.LEFT_ANKLE, BLAZEPOSE_KEYPOINTS.LEFT_FOOT_INDEX],
  [BLAZEPOSE_KEYPOINTS.LEFT_HEEL, BLAZEPOSE_KEYPOINTS.LEFT_FOOT_INDEX],

  // Right leg
  [BLAZEPOSE_KEYPOINTS.RIGHT_HIP, BLAZEPOSE_KEYPOINTS.RIGHT_KNEE],
  [BLAZEPOSE_KEYPOINTS.RIGHT_KNEE, BLAZEPOSE_KEYPOINTS.RIGHT_ANKLE],
  [BLAZEPOSE_KEYPOINTS.RIGHT_ANKLE, BLAZEPOSE_KEYPOINTS.RIGHT_HEEL],
  [BLAZEPOSE_KEYPOINTS.RIGHT_ANKLE, BLAZEPOSE_KEYPOINTS.RIGHT_FOOT_INDEX],
  [BLAZEPOSE_KEYPOINTS.RIGHT_HEEL, BLAZEPOSE_KEYPOINTS.RIGHT_FOOT_INDEX],
]
